// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Rcpp_asInteger_Enumfactor
NumericVector Rcpp_asInteger_Enumfactor(const NumericVector& x, const NumericVector& indices);
RcppExport SEXP _enumfactor_Rcpp_asInteger_Enumfactor(SEXP xSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_asInteger_Enumfactor(x, indices));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_enumfactor_Rcpp_asInteger_Enumfactor", (DL_FUNC) &_enumfactor_Rcpp_asInteger_Enumfactor, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_enumfactor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
