# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_asInteger_Enumfactor <- function(x, indices) {
    .Call(`_enumfactor_Rcpp_asInteger_Enumfactor`, x, indices)
}

Rcpp_asNumeric_Enumfactor <- function(x, indices) {
    .Call(`_enumfactor_Rcpp_asNumeric_Enumfactor`, x, indices)
}

